/**
 * High-Resolution Canvas Collage Generator.
 * Supports DYNAMIC_GRID, POLAROID, HONEYCOMB, and HERO_GRID layouts.
 */
export class CollageRenderer {
  renderCollage(canvas, persons, style = 'DYNAMIC_GRID') {
    const ctx = canvas.getContext('2d');
    const width = 1920;
    const height = 1080;
    canvas.width = width;
    canvas.height = height;

    // Background Gradient
    const bgGrad = ctx.createLinearGradient(0, 0, width, height);
    bgGrad.addColorStop(0, '#0a0e1a');
    bgGrad.addColorStop(0.5, '#13192b');
    bgGrad.addColorStop(1, '#05070d');
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, width, height);

    // Decorative subtle geometric background grid
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.03)';
    ctx.lineWidth = 1;
    for (let x = 0; x < width; x += 60) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, height);
      ctx.stroke();
    }
    for (let y = 0; y < height; y += 60) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }

    if (!persons || persons.length === 0) {
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 36px Outfit, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('No unique persons detected', width / 2, height / 2);
      return;
    }

    const count = persons.length;
    const padding = 40;
    const headerHeight = 90;

    // Header Title
    ctx.fillStyle = '#6366f1';
    ctx.font = 'bold 32px Outfit, sans-serif';
    ctx.textAlign = 'left';
    ctx.fillText(`UNIQUE PERSONS (${count})`, padding, 60);

    ctx.fillStyle = '#94a3b8';
    ctx.font = '500 20px Plus Jakarta Sans, sans-serif';
    ctx.textAlign = 'right';
    ctx.fillText('Generated by UniquePersonCollage AI', width - padding, 60);

    const availableW = width - (padding * 2);
    const availableH = height - headerHeight - padding;

    if (style === 'DYNAMIC_GRID' || style === 'POLAROID') {
      const cols = Math.ceil(Math.sqrt(count));
      const rows = Math.ceil(count / cols);
      const gap = 24;

      const tileW = (availableW - (cols - 1) * gap) / cols;
      const tileH = (availableH - (rows - 1) * gap) / rows;

      persons.forEach((p, idx) => {
        const c = idx % cols;
        const r = Math.floor(idx / cols);
        const x = padding + c * (tileW + gap);
        const y = headerHeight + r * (tileH + gap);

        this.drawPersonCard(ctx, p, x, y, tileW, tileH, style === 'POLAROID');
      });
    } else if (style === 'HONEYCOMB') {
      const cols = Math.ceil(Math.sqrt(count));
      const rows = Math.ceil(count / cols);
      const gap = 30;

      const tileW = (availableW - (cols - 1) * gap) / cols;
      const tileH = (availableH - (rows - 1) * gap) / rows;
      const radius = Math.min(tileW, tileH) / 2.5;

      persons.forEach((p, idx) => {
        const c = idx % cols;
        const r = Math.floor(idx / cols);
        const cx = padding + c * (tileW + gap) + tileW / 2;
        const cy = headerHeight + r * (tileH + gap) + tileH / 2 - 20;

        this.drawCircularPerson(ctx, p, cx, cy, radius);
      });
    } else if (style === 'HERO_GRID') {
      if (count === 1) {
        this.drawPersonCard(ctx, persons[0], padding, headerHeight, availableW, availableH, false);
      } else {
        const heroW = availableW * 0.42;
        const heroH = availableH;
        this.drawPersonCard(ctx, persons[0], padding, headerHeight, heroW, heroH, false);

        const subCount = count - 1;
        const subCols = Math.ceil(Math.sqrt(subCount));
        const subRows = Math.ceil(subCount / subCols);
        const subX = padding + heroW + 30;
        const subW = availableW - heroW - 30;
        const gap = 20;

        const tileW = (subW - (subCols - 1) * gap) / subCols;
        const tileH = (availableH - (subRows - 1) * gap) / subRows;

        for (let i = 1; i < count; i++) {
          const p = persons[i];
          const sIdx = i - 1;
          const c = sIdx % subCols;
          const r = Math.floor(sIdx / subCols);
          const x = subX + c * (tileW + gap);
          const y = headerHeight + r * (tileH + gap);

          this.drawPersonCard(ctx, p, x, y, tileW, tileH, false);
        }
      }
    }
  }

  drawPersonCard(ctx, person, x, y, w, h, isPolaroid) {
    ctx.save();

    // Card background
    ctx.fillStyle = isPolaroid ? '#ffffff' : '#1e293b';
    ctx.shadowColor = 'rgba(0,0,0,0.5)';
    ctx.shadowBlur = 16;
    ctx.shadowOffsetY = 8;
    this.roundRect(ctx, x, y, w, h, isPolaroid ? 8 : 16);
    ctx.fill();
    ctx.shadowBlur = 0;

    // Draw Image
    const imgPad = isPolaroid ? 12 : 8;
    const imgBottomPad = isPolaroid ? 64 : 50;
    const imgW = w - imgPad * 2;
    const imgH = h - imgPad - imgBottomPad;

    if (person.bestDetection && person.bestDetection.cropCanvas) {
      ctx.save();
      this.roundRect(ctx, x + imgPad, y + imgPad, imgW, imgH, isPolaroid ? 4 : 12);
      ctx.clip();
      ctx.drawImage(person.bestDetection.cropCanvas, x + imgPad, y + imgPad, imgW, imgH);
      ctx.restore();
    }

    // Name & Stats
    ctx.fillStyle = isPolaroid ? '#0f172a' : '#f8fafc';
    ctx.font = `bold ${Math.max(16, Math.min(26, w * 0.08))}px Outfit, sans-serif`;
    ctx.textAlign = 'center';
    ctx.fillText(person.name, x + w / 2, y + h - (isPolaroid ? 34 : 28));

    ctx.fillStyle = isPolaroid ? '#64748b' : '#94a3b8';
    ctx.font = `500 ${Math.max(12, Math.min(16, w * 0.05))}px Plus Jakarta Sans, sans-serif`;
    ctx.fillText(`${person.appearanceCount} appearances • ${person.screenTime}`, x + w / 2, y + h - (isPolaroid ? 14 : 10));

    ctx.restore();
  }

  drawCircularPerson(ctx, person, cx, cy, radius) {
    ctx.save();

    // Glow ring
    ctx.beginPath();
    ctx.arc(cx, cy, radius + 4, 0, Math.PI * 2);
    ctx.fillStyle = 'rgba(99, 102, 241, 0.4)';
    ctx.fill();

    // Mask circle
    ctx.beginPath();
    ctx.arc(cx, cy, radius, 0, Math.PI * 2);
    ctx.closePath();
    ctx.save();
    ctx.clip();

    if (person.bestDetection && person.bestDetection.cropCanvas) {
      ctx.drawImage(person.bestDetection.cropCanvas, cx - radius, cy - radius, radius * 2, radius * 2);
    } else {
      ctx.fillStyle = '#1e293b';
      ctx.fill();
    }
    ctx.restore();

    // Outer border
    ctx.lineWidth = 3;
    ctx.strokeStyle = '#6366f1';
    ctx.stroke();

    // Label
    ctx.fillStyle = '#f8fafc';
    ctx.font = 'bold 18px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(person.name, cx, cy + radius + 24);

    ctx.fillStyle = '#94a3b8';
    ctx.font = '500 13px Plus Jakarta Sans, sans-serif';
    ctx.fillText(`${person.appearanceCount} scenes`, cx, cy + radius + 42);

    ctx.restore();
  }

  roundRect(ctx, x, y, width, height, radius) {
    ctx.beginPath();
    ctx.moveTo(x + radius, y);
    ctx.lineTo(x + width - radius, y);
    ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
    ctx.lineTo(x + width, y + height - radius);
    ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
    ctx.lineTo(x + radius, y + height);
    ctx.quadraticCurveTo(x, y + height, x, y + height - radius);
    ctx.lineTo(x, y + radius);
    ctx.quadraticCurveTo(x, y, x + radius, y);
    ctx.closePath();
  }
}
